### ISSUE TITLE
Screens for Inventory/Nodes (READ)

### ISSUE THREAD

**Issue by rufer7** [dfensgmbh/biz.dfch.CS.Appclusive.UI#10]
- [x] Read

![inventory-node](https://cloud.githubusercontent.com/assets/5937292/11469943/2ea47ffc-975a-11e5-9e73-5f01b27d4ef1.png)
![inventory-node-2](https://cloud.githubusercontent.com/assets/5937292/11469944/2ea52092-975a-11e5-9b7e-f72abb804191.png)
![inventory](https://cloud.githubusercontent.com/assets/5937292/11469942/2ea130ea-975a-11e5-8ae0-d95e20551a7b.png)

**Comment by ChrEggenberger** [comment]
Paging missing
