### ISSUE TITLE
Issues on Tenant selection

### ISSUE THREAD

**Issue by ChrEggenberger** [dfensgmbh/biz.dfch.CS.Appclusive.UI#101]
* [x] Select a real tenant as default after logging in (now there is "all tenats" select and the user needs to select a tenant.)
* [x] still all nodes (except system root) are found even if a tenant is selected

**Comment by rufer7** [comment]
@ChrEggenberger I verified the second point in the issue description with an user which is not in the role `UberAdmin` and it worked as expected so I'll close this issue. The reason why all nodes were shown is, that the administrator user is in the UberAdmin role that implicitly disables the tenant filter in the backend.
