### ISSUE TITLE
Style broken when connection over HTTPS

### ISSUE THREAD

**Issue by rufer7** [dfensgmbh/biz.dfch.CS.Appclusive.UI#103]

**Comment by ChrEggenberger** [comment]
I ran the application locally on https and could not find a problem. Where do you encounter it? url, page?
It could have something to do with certificates or/and firewalls too.

**Comment by rufer7** [comment]
@ChrEggenberger I actually recognized that it's not a `HTTPS` specific problem. There are two different "names/URLs" to access the machine. When connecting via HTTPS only for one name the problem occurs, so I think as you said it's a certificate or firewall related problem
