### ISSUE TITLE
Requester selection when adding VDI for another user

### ISSUE THREAD

**Issue by rufer7** [dfensgmbh/biz.dfch.CS.Appclusive.UI#105]
On the screen below it should be possible to select a user from users table as requester.

**Important**: The requester property changed a few weeks ago to RequesterId. There the Id of the selected user has to be put in.

![12 02](https://cloud.githubusercontent.com/assets/5937292/13002208/f7f2dce0-d16c-11e5-8e55-137ae913b842.png)

**Comment by ChrEggenberger** [comment]
Yes, this was never implemented. It is now.
fyi: To test I created the "VDI Test catalogue" catalogue with VDI-items
