### ISSUE TITLE
Enable Action invocation on Nodes

### ISSUE THREAD

**Issue by rufer7** [dfensgmbh/biz.dfch.CS.Appclusive.UI#107]
As in the customer portal there should be a possibility to invoke actions on a `Node`. The available actions can be fetched with the following request

`POST ~/api/Core/Nodes(ID)/AvailableActions` (empty body)

Actions can be invoked with the following request

```
POST ~/api/Core/Nodes(ID)/InvokeAction

{
  "Name":"ActionName",
  "Parameters":"ActionParameters"
}
```

Action parameters can be left empty for the moment

**Comment by rufer7** [comment]
@ChrEggenberger can you please implement that as soon as possible?

**Comment by ChrEggenberger** [comment]
Inside the detail tab of the node detail on there is a dropdown with all available action on the node. Text can be changed in GeneralResources.resx:
ActOnNode: execute
ActOnNodeConfirm: Do you really want to execute this action?

**Comment by dfch** [comment]
@ChrEggenberger thanks for the quick implementation! just a minor clarification: the actual translation shall not be fed from a resource file but from the `~/Products(nnL)/Metadata` action. Or are you only referring to to the translation of the confirmation dialogue labels?

**Comment by ChrEggenberger** [comment]
@dfch The translations I mentioned are only concerning the text on the button and the confirmation message. The actions themselves are not translated now. Marc mentioned the fact that they should come from the metadata of the product. If you let me know where in the whole xml they can be found I can add that as well.
