### ISSUE TITLE
Spinner stays after adding User to Role

### ISSUE THREAD

**Issue by rufer7** [dfensgmbh/biz.dfch.CS.Appclusive.UI#108]
As shown in the screenshot below the spinner stays after adding an `User` to a `Role`. In the database the mapping was added successfully and as well the success message in the UI appeared. Same happens if user gets removed from a `Role`

![28 02](https://cloud.githubusercontent.com/assets/5937292/13378412/27d1c5e8-de06-11e5-88e2-24f11764dd1f.png)

**Comment by ChrEggenberger** [comment]
I gave it I quick try, but I can not reproduce the error. It works with all my browsers. Any more hints?

**Comment by rufer7** [comment]
@ChrEggenberger I tried to reproduce it again in LAB3. 

I took some screenshots to allow you to reproduce the error if you are interested and have time. Otherwise let me know then I'll try to fix it myself.

1. ![1](https://cloud.githubusercontent.com/assets/5937292/13636516/a66dabe8-e602-11e5-9ae0-7435e73f06cb.png)
1. ![2](https://cloud.githubusercontent.com/assets/5937292/13636523/aaccf31a-e602-11e5-94f5-1ec8e7a6369c.png)
1. ![3](https://cloud.githubusercontent.com/assets/5937292/13636527/adff1bb2-e602-11e5-9e0d-7ebc542561f1.png)
1. ![4](https://cloud.githubusercontent.com/assets/5937292/13636530/b1faaed4-e602-11e5-9c0d-050b6d288509.png)
1. ![5](https://cloud.githubusercontent.com/assets/5937292/13636540/b5b95cd2-e602-11e5-8163-052582b7045b.png)
1. ![6](https://cloud.githubusercontent.com/assets/5937292/13636547/b93f7dbe-e602-11e5-9c1b-6349060e47e3.png)

Chrome `Version 49.0.2623.87 m`

**Comment by rufer7** [comment]
![spinnter-stays](https://cloud.githubusercontent.com/assets/5937292/13949118/d41e1d40-f023-11e5-9e10-749162cc80d9.png)

**Comment by rufer7** [comment]
When publishing the `Web Deploy Package` the zip file created by this process does not contain `notify.js`

**Comment by rufer7** [comment]
Verified in LAB3 -> now ok
