### ISSUE TITLE
Screens for Orders and OrderItems (READ & DELETE)

### ISSUE THREAD

**Issue by rufer7** [dfensgmbh/biz.dfch.CS.Appclusive.UI#11]
**Orders**
- [x] Read
- [x] Delete (postponed)

**OrderItems**
- [x] Read
- [x] Delete (postponed - not implemented on server side)

![order-3](https://cloud.githubusercontent.com/assets/5937292/11469959/581a8a16-975a-11e5-9b9f-dd26a96ef62a.png)
![orders](https://cloud.githubusercontent.com/assets/5937292/11469962/581d37d4-975a-11e5-8c47-ce0da35cc187.png)
![order](https://cloud.githubusercontent.com/assets/5937292/11469961/581cf4fe-975a-11e5-96f4-35eafec239fc.png)
![order-2](https://cloud.githubusercontent.com/assets/5937292/11469960/581bfc20-975a-11e5-9d1b-d1e1f0d31654.png)
![order-item-details](https://cloud.githubusercontent.com/assets/5937292/11470020/cb347232-975a-11e5-9de5-a5d8aa85049f.png)

**Comment by ChrEggenberger** [comment]
@rufer7 I assume the date in the list is the order-created-date. Correct?
There are no orders in Lab3. What is the easiest way the get some sampla data in the database?

**Comment by rufer7** [comment]
sample data are available on LAB3

**Comment by ChrEggenberger** [comment]
* Delete order-items disabled, because of NotImplementedException on server side
* rest is done
