### ISSUE TITLE
Nodes Tree not showing up anymore

### ISSUE THREAD

**Issue by rufer7** [dfensgmbh/biz.dfch.CS.Appclusive.UI#116]
When navigating to graphical tree view of Nodes the place where the tree should appear stays empty. This has to be fixed so that the tree shows up again and can be expanded as before.

**Comment by rufer7** [comment]
@oliverluethi this one has second highest prio

**Comment by oliverluethi** [comment]
@rufer7 Do you have a specific node which don't work as an example?

**Comment by rufer7** [comment]
@oliverluethi seems that it works again... In INT11 I could reproduce the problem. In INT11 the inlinecount fix is not yet deployed. During troubleshooting I saw that the tree was not rendered anymore becuase of the inlinecount bug, so we can close the issue. Thanks anyway

**Comment by oliverluethi** [comment]
@rufer7 Sorry, I need to reopen this issue. The paging won't work with large tree nodes (old paging code).

**Comment by rufer7** [comment]
Fixed by #119
