### ISSUE TITLE
Screens for CatalogueItems (CRUD)

### ISSUE THREAD

**Issue by rufer7** [dfensgmbh/biz.dfch.CS.Appclusive.UI#12]
- [x] Read
- [x] Add to Cart (POST to `~/CartItems`)
- [x] Create (postponed)
- [x] Update (postponed)
- [x] Delete (postponed)

![catalogue-items](https://cloud.githubusercontent.com/assets/5937292/11470039/f04349a4-975a-11e5-9fe2-56060301bcd0.png)

**Comment by ChrEggenberger** [comment]
Creating and saving catalog items creates often error messages but without valuable information
-> better validation and information of user
