### ISSUE TITLE
Screens for Carts and CartItems (READ, UPDATE, DELETE)

### ISSUE THREAD

**Issue by rufer7** [dfensgmbh/biz.dfch.CS.Appclusive.UI#13]
**Cart**
- [x] Read
- [x] Checkout cart (POST to `~/Orders`)
- [x] Update (postponed - not implemented on server side)
- [x] Delete (postponed)

**CartItems**
- [x] Read
- [x] Update (postponed)
- [x] Delete (postponed)

![cart-item-edit](https://cloud.githubusercontent.com/assets/5937292/11470125/a6cb60bc-975b-11e5-9be0-abef4d648b54.png)
![carts](https://cloud.githubusercontent.com/assets/5937292/11470127/a6ccb5a2-975b-11e5-9949-b2ac2476b07b.png)
![cart](https://cloud.githubusercontent.com/assets/5937292/11470128/a6cce7de-975b-11e5-9b0c-efbcd6c4feb0.png)
![cart-2](https://cloud.githubusercontent.com/assets/5937292/11470129/a6cd7bb8-975b-11e5-8a9d-1a6e03280e07.png)
![cart-item](https://cloud.githubusercontent.com/assets/5937292/11470130/a6ced04e-975b-11e5-8294-9d72921a00ef.png)

**Comment by ChrEggenberger** [comment]
Check out card is implemented and works, except that there is the same problem like with the approval: API return a job and sends a wrong contect type (appplication/xml instead of application/atom+xml)
