### ISSUE TITLE
Screens for Approvals (READ, UPDATE)

### ISSUE THREAD

**Issue by rufer7** [dfensgmbh/biz.dfch.CS.Appclusive.UI#15]
- [x] Read
- [x] Update
  - [x] Approve
  - [x] Decline
- [x] Navigation to Order

![approvals](https://cloud.githubusercontent.com/assets/5937292/11470163/f0b02e56-975b-11e5-93b1-a17c62cc9ebc.png)
![approval](https://cloud.githubusercontent.com/assets/5937292/11470162/f0ae2656-975b-11e5-8412-47e98c3d0198.png)
![approval-approve](https://cloud.githubusercontent.com/assets/5937292/11470161/f0ad7b34-975b-11e5-89d5-a587694e8ec4.png)
![approval-decline](https://cloud.githubusercontent.com/assets/5937292/11470160/f0aaa148-975b-11e5-8db4-123a4c32ba9c.png)

**Comment by ChrEggenberger** [comment]
@rufer7 Updating approvals I get "An error occurred while processing this request. " even if I do not change anything
Can you tell me wher I can find the appcusive logs? On 172.19.155.33 under C:\Logs\biz.dfch.PS.System.Logging are no new files.

**Comment by rufer7** [comment]
logfile can be found here `%TEMP%\appclusive.log`

**Comment by ChrEggenberger** [comment]
Code written and approvals are sent successfully to server. But until now no approval could be processed successfully. Errors
* no job can be found
* Specified argument was out of the range of valid values. 
Parameter name: stateTransition is invalid: 'Created' @ 'continue''

**Comment by rufer7** [comment]
@chreggenberger send 'Continue" instead of 'continue' then it should work

**Comment by ChrEggenberger** [comment]
now the approval is updated but it still returns an exception 

73c6abf2-0d35-4614-b722-2dcd43b0d944-START [MERGE http://172.19.115.33/Appclusive/api/Core/Approvals(2L)] [Approvals.Patch] [W2012R2-T6-10\Administrator@unknown]
Creating state machine for entityType 'biz.dfch.CS.Appclusive.Core.OdataServices.Core.Approval'...
Creating state machine for entityType 'biz.dfch.CS.Appclusive.Core.OdataServices.Core.Approval' COMPLETED
2004 Job ModifiedPrevious {"ModifiedBy":"SYSTEM","Status":"Created"}
New      {"ModifiedBy":"W2012R2-T6-10\\Administrator","Status":"Approved"}
Creating state machine for entityType 'biz.dfch.CS.Appclusive.Core.OdataServices.Core.Order'...
Creating state machine for entityType 'biz.dfch.CS.Appclusive.Core.OdataServices.Core.Order' COMPLETED
2003 Job ModifiedPrevious {"Status":"Approval"}
New      {"Status":"WaitingToRun"}
START sending message to facility 'NOTIFY-WFE'...
73c6abf2-0d35-4614-b722-2dcd43b0d944-END
Creating state machine for entityType 'biz.dfch.CS.Appclusive.Core.OdataServices.Core.Approval'...
Creating state machine for entityType 'biz.dfch.CS.Appclusive.Core.OdataServices.Core.Approval' COMPLETED
I am an approval (biz.dfch.CS.Appclusive.Core.OdataServices.Core.Approval) with job.Status 'Approved' [@2004]
ArbitraryContentException@biz.dfch.CS.Appclusive.Core: '73c6abf2-0d35-4614-b722-2dcd43b0d944-EX [MERGE http://172.19.115.33/Appclusive/api/Core/Approvals(2L)] [W2012R2-T6-10\Administrator@undefined]
Exception of type 'biz.dfch.CS.Appclusive.Core.Security.ArbitraryContentException' was thrown.'
[Exception of type 'biz.dfch.CS.Appclusive.Core.Security.ArbitraryContentException' was thrown.]
   at biz.dfch.CS.Appclusive.Core.OdataServices.Core.ApprovalsController.<Patch>d__d.MoveNext() in c:\development\projects\GitHub\biz.dfch.CS.Appclusive\src\biz.dfch.CS.Appclusive.Core\OdataServices\Core\ApprovalsController.cs:line 139
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()

**Comment by rufer7** [comment]
@ChrEggenberger FYI I added an additional "checkbox" for the navigation to the order

**Comment by ChrEggenberger** [comment]
Hter is still a problem with sending the response for an approval patch on the server side. But the erest is done and the exception witch occurse is not shown (TODO in the code to remov this)
