### ISSUE TITLE
Screens for ManagementUris (CRUD)

### ISSUE THREAD

**Issue by rufer7** [dfensgmbh/biz.dfch.CS.Appclusive.UI#21]
- [x] Read
- [x] Create
- [x] Update
- [x] Delete

![mgmt-uris](https://cloud.githubusercontent.com/assets/5937292/11470345/1e110cc0-975d-11e5-8daa-4e0604237af3.png)
![mgmt-uri](https://cloud.githubusercontent.com/assets/5937292/11470346/1e14c7ca-975d-11e5-8d64-b2e82b93a028.png)

**Comment by ChrEggenberger** [comment]
Exception when updating incuding a ManagementCredentialId.

**Comment by dfch** [comment]
@ChrEggenberger could you please add some details including (Fiddler) request/response?

**Comment by ChrEggenberger** [comment]
Problem is solved.
