### ISSUE TITLE
Screens for Gates (CRUD)

### ISSUE THREAD

**Issue by rufer7** [dfensgmbh/biz.dfch.CS.Appclusive.UI#22]
- [x] Read
- [x] Create
- [x] Update
- [x] Delete

![gates](https://cloud.githubusercontent.com/assets/5937292/11470361/35700bdc-975d-11e5-9b31-f8cd941dbf7c.png)
![gate-add](https://cloud.githubusercontent.com/assets/5937292/11470362/35719678-975d-11e5-825b-77a43d3c69a4.png)

**Comment by ChrEggenberger** [comment]
@rufer7 There are no gates in the database for testing. Can you add some?

**Comment by rufer7** [comment]
sample data are available on LAB3
