### ISSUE TITLE
Create toasts

### ISSUE THREAD

**Issue by rufer7** [dfensgmbh/biz.dfch.CS.Appclusive.UI#23]

**Comment by rufer7** [comment]
@ChrEggenberger I think you implemented that already, right? If yes, you could close this issue

**Comment by ChrEggenberger** [comment]
@rufer7 No idea what toasts are.  That commit was probably attached to the wrong issue

**Comment by rufer7** [comment]
@ChrEggenberger toasts are these notifications you implemented on top right side
