### ISSUE TITLE
Paging and/or filters for large lists

### ISSUE THREAD

**Issue by ChrEggenberger** [dfensgmbh/biz.dfch.CS.Appclusive.UI#28]
paging for
* [x] inventory/nodes
* [x] orders
* [x] products
* [x] jobs
* [x] approvals

**Comment by ChrEggenberger** [comment]
Paging an all lists implemented
![paging](https://cloud.githubusercontent.com/assets/15813194/11686325/20494442-9e80-11e5-84dd-51eb978222ad.PNG)
... -> there is more data

**Comment by dfch** [comment]
@ChrEggenberger I just noticed that there is no paging for AuditTrail or Catalogues implemented. Could you pls implement paging for these screens as well and also check if now all list screens have this enabled? thx

**Comment by ChrEggenberger** [comment]
@dfch There is pagin implemented an all main lists, including Audittrail and catalogues (Audittrail in commit 6f10f169aeceb566d26782d6674c744d9849fd33  'Donnerstag, 10. Dezember 2015 10:22:27' not in develop branch yet). But the page numbers do only show when there is more data availble.
Pages size can be configured in PortqalConfig.cs, but could just as well be in the config file or whereever...

namespace biz.dfch.CS.Appclusive.UI.Models
{
    public class PortalConfig
    {
        public static int Pagesize = 20;
    }
}

I think we can close this one. there is another issue to paging too  #46

**Comment by dfch** [comment]
@ChrEggenberger good for me - thx
