### ISSUE TITLE
Create Tile View

### ISSUE THREAD

**Issue by dfch** [dfensgmbh/biz.dfch.CS.Appclusive.UI#3]
**Example**

![tile-view](https://cloud.githubusercontent.com/assets/5937292/13636645/3f555662-e603-11e5-8e16-c5e31179dd3b.png)

**Comment by rufer7** [comment]
@dfch can we close this issue?

**Comment by dfch** [comment]
I would keep this open as we do not have this yet

**Comment by rufer7** [comment]
Moved to another repository
