### ISSUE TITLE
Enable internationalization

### ISSUE THREAD

**Issue by rufer7** [dfensgmbh/biz.dfch.CS.Appclusive.UI#38]

**Comment by ChrEggenberger** [comment]
I already changed it to de-CH, so the dates are in a understandable format.
What is your idea, how should it be. Use automatically the language of the browser?

**Comment by rufer7** [comment]
@ChrEggenberger the idea is to have different resource files that hold translations for the keys which should then be used in the html pages so that the UI gets translated if browser language gets changed. Concerning language choice I would set the language according the selected browser language... If needed we could later add a dropdown or some flags for choosing the language, but for now setting lanaguage according browser language is sufficient

**Comment by ChrEggenberger** [comment]
* All text is in ressourcefiles in English
* To have a "normal" Date-Formatting there is fix de-CH set in the web.config

**Comment by rufer7** [comment]
Concerning the Date-Formatting I would not set a fix locale. I would still set language according browser language.

By the way I'll do a release today, so all the finished issues get closed
