### ISSUE TITLE
Switch from MERGE to PATCH

### ISSUE THREAD

**Issue by rufer7** [dfensgmbh/biz.dfch.CS.Appclusive.UI#40]

**Comment by rufer7** [comment]
@dfch probably you could provide a code snippet here as well?

**Comment by dfch** [comment]
* [DataServiceContext.SaveChangesDefaultOptions Property](https://msdn.microsoft.com/en-us/library/system.data.services.client.dataservicecontext.savechangesdefaultoptions(v=vs.110).aspx)
* [PatchOnUpdate](https://msdn.microsoft.com/en-us/library/system.data.services.client.savechangesoptions(v=vs.113).aspx)

**Comment by ChrEggenberger** [comment]
DONE
