### ISSUE TITLE
Internationalisation

### ISSUE THREAD

**Issue by rufer7** [dfensgmbh/biz.dfch.CS.Appclusive.UI#42]
- [x] Implement internationalisation on all screens (all properties)
- [x] Messages
- [x] Navigation and CamlCase properties
- [x] Tipetexts (Delete)

**Comment by rufer7** [comment]
@ChrEggenberger I think this one is done as well, right? If yes you can close this issue

**Comment by ChrEggenberger** [comment]
@rufer7 No not completely. There are still entries for ALL properteis of the entities missing. I will do that by code and reflection

**Comment by ChrEggenberger** [comment]
Unittest CreateResourceFile.GenerateTextsForAllProperties()  updates the resource file GeneralResources.resx with all public properties off all types in the namespace biz.dfch.CS.Appclusive.UI.Models. Pascal cased properties are converted to "normal" strings:

property CreatedBy:
Resource Key: CreatedBy
Value: Created by
