### ISSUE TITLE
Improve paging

### ISSUE THREAD

**Issue by rufer7** [dfensgmbh/biz.dfch.CS.Appclusive.UI#46]
![jquery-pagination-plugin-for-bootstrap](https://cloud.githubusercontent.com/assets/5937292/11700255/0cfd2ac2-9ec9-11e5-9acf-8da017fc557a.png)

Paging should be implemented like shown in the following screenshot

![09 12](https://cloud.githubusercontent.com/assets/5937292/11700225/e0415332-9ec8-11e5-8153-2d5add018af8.png)

* [x] Improve paging in general
* [x] Implement paging to CatalogueItem list

**Comment by ChrEggenberger** [comment]
What is the difference to the paging I implemented an all lists?
What should be improved?
________________________________
Von: Rufer<mailto:notifications@github.com>
Gesendet: ‎09.‎12.‎2015 23:03
An: dfensgmbh/biz.dfch.CS.Appclusive.UI<mailto:biz.dfch.CS.Appclusive.UI@noreply.github.com>
Cc: Christian Eggenberger<mailto:eggenberger@afca.ch>
Betreff: [biz.dfch.CS.Appclusive.UI] Improve paging (#46)


[09 12]<https://cloud.githubusercontent.com/assets/5937292/11700161/8fa2e3c8-9ec8-11e5-95fa-f98e28cf3b75.png>

Paging should be implemented like shown in the following screenshot

[09 12]<https://cloud.githubusercontent.com/assets/5937292/11700225/e0415332-9ec8-11e5-8153-2d5add018af8.png>

  *    Improve paging in general
  *    Add paging to CatalogueItem list

**Comment by rufer7** [comment]
@ChrEggenberger the difference is that your paging menu initially only shows one button with the actual page (no previous and next button) and expands another button as soon as the butto '...' is clicked (see screenshots for difference.

**Comment by ChrEggenberger** [comment]
@rufer7 The ODATA count Method is not supported in the appclusive API:
request:
GET http://172.19.115.33/Appclusive/api/Core/ManagementCredentials()/$count HTTP/1.1
DataServiceVersion: 2.0;NetFx
MaxDataServiceVersion: 3.0;NetFx
Accept: text/plain
Accept-Charset: UTF-8
User-Agent: Microsoft ADO.NET Data Services
Host: 172.19.115.33
Connection: Keep-Alive

Response:
HTTP/1.1 404 Not Found
Cache-Control: no-cache
Pragma: no-cache
Content-Type: application/json; charset=utf-8
Expires: -1
Server: Microsoft-IIS/8.5
Set-Cookie: ASP.NET_SessionId=uj2sdktvnkl40vbbr1aewzjb; path=/; HttpOnly
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET
Date: Thu, 10 Dec 2015 08:34:24 GMT
Content-Length: 40

{"Message":"The OData path is invalid."}

I can not load all and count them on the client. Therefore we do not now how many pages there are in total.

Scince this UI was supposed to be a quick and dirty admin UI I thought it is not worth the time to solve the problem on the server. We can just do it simple and show a next button if there are more data to load.

Any suggestions?

**Comment by rufer7** [comment]
@ChrEggenberger first of all you're right `$count` is not working but it could be activated on the Appclusive project. Another option to get the count is using the following query option `~/api/Core/ManagementCredentials()?$inlinecount=allpages`. I would suggest to keep it easy and to implement a `previous` and `next` button instead of showing paging information.

**Comment by dfch** [comment]
@ChrEggenberger @rufer7 the advantage of using `$inlinecount` is that (along with the paging) you get all the information with the `DataServiceResponse` (including next link etc). 
I suggest to use `$inlinecount` as the customer portal is using this as well.
