### ISSUE TITLE
Implement screens responsive

### ISSUE THREAD

**Issue by rufer7** [dfensgmbh/biz.dfch.CS.Appclusive.UI#47]
The UI is supposed to be used by TechAdmins as well with a limited distribution potentially to end user customers. This was actually not foreseen at the start.

**Comment by ChrEggenberger** [comment]
@rufer7 So this is definitely not a back-office-quick-and-dirty-UI anymore?!!?
This is quit a different approach to the task....

**Comment by trumpetchris** [comment]
If nav-bar breaks on two lines it hides the body.

**Comment by rufer7** [comment]
@trumpetchris the navbar is now fixed, so the above comment is no longer valid right?
