### ISSUE TITLE
Update UI against Test UI against Appclusive 1.1.0

### ISSUE THREAD

**Issue by dfch** [dfensgmbh/biz.dfch.CS.Appclusive.UI#49]
This is a follow-up to #41

* [x] ACE
* [x] ACL
* [x] Approval
* [x] Cart, CartItem
* [x] Catalogue, CatalogueItems
* [x] CimiTarget
* [x] ContractMapping -> #54 
* [x] CostCenter
* [x] Customer -> #54 
* [x] EntityKind
* [x] Gate
* [x] Job
* [x] KeyNameValue
* [x] ManagementCredential
* [x] ManagementUri
* [x] Node
* [x] Order, OrderItems
* [x] Product
* [x] Tenant
* [x] User
* [x] Vdi
* [x] AuditTrail
* [x] Endpoint

All defects from #41 must be listed as issues and resolved. The order/ importance will be defined by @rufer7 .

**Comment by ChrEggenberger** [comment]
Infos:
* Products: no Version anymore
* Job has properties Tid, Tenant and TenantId

**Comment by rufer7** [comment]
@ChrEggenberger 

* Exactly, there is no more version property on product
* As every other entity `Job` has `Tid` and `Tenant`. There is another property `TenantId` which allows to specifiy for which tenant the job has to be executed
