### ISSUE TITLE
SectionGroup vs. ConnectionStrings

### ISSUE THREAD

**Issue by rufer7** [dfensgmbh/biz.dfch.CS.Appclusive.UI#50]
@ChrEggenberger  why did you create a new section group in the `web.config` file for `AppculsiveApiDiagnosticsUrl` and `AppculsiveApiCoreUrl`. There is already a section `connectionStrings` which could be used for defining these URLs!?

**Comment by ChrEggenberger** [comment]
@rufer7 Because I/we usually use the "modern" strongly typed way of properties and settings and the connectionStrings section is there by default and empty. But how ever it fits better in the appclusive way of doing thing is fine for me :-)

**Comment by rufer7** [comment]
@ChrEggenberger ah ok, thank for the answer. I didn't use the "modern" way until know but I can see the benefits. I'll close the issue and we will let it like you implemented it as the issue was only an issue of type `question`
