### ISSUE TITLE
Missing controllers on Appclusive.Api.Core service

### ISSUE THREAD

**Issue by ChrEggenberger** [dfensgmbh/biz.dfch.CS.Appclusive.UI#53]
On the API Core Sevice there are following controllers missing:
* Customers
* ContractMappings

**Comment by dfch** [comment]
this is currently a low prio task

**Comment by rufer7** [comment]
@ChrEggenberger now controllers for the following entities are available:

* Permissions
* Roles
* Customers
* ContractMappings
