### ISSUE TITLE
Selection for property Type on product?

### ISSUE THREAD

**Issue by ChrEggenberger** [dfensgmbh/biz.dfch.CS.Appclusive.UI#61]
Should there be a selection for the Type property on Product?
```c#
        [Required]
        public string Type { get; set; }
```

**Comment by dfch** [comment]
@ChrEggenberger `Type` is used here more like a `Category` or *arbitrary" `Tag` that a product designer can freely choose. We do not enforce anything here. 
So the answer is no, there should not be a selection for the `Type`.
