### ISSUE TITLE
Missing Navigation property Customer und CustomerId on Tenant

### ISSUE THREAD

**Issue by ChrEggenberger** [dfensgmbh/biz.dfch.CS.Appclusive.UI#67]
Add Customer and CustomerID property to tenant in API

(Code in UI is there but does not work without API)

**Comment by dfch** [comment]
@ChrEggenberger `Customer` has a *back reference*  to the `Tenant` entity (not the other way round). So you would have to query `~/Core/Customers?$filter=Tid eq '58e2d334-32be-499e-a5a7-85823826e3bf'`

**Comment by rufer7** [comment]
@ChrEggenberger should now be fixed since latest deployment in LAB3
