### ISSUE TITLE
returnAction-ID (rId) must have the same type as the id of the entity

### ISSUE THREAD

**Issue by trumpetchris** [dfensgmbh/biz.dfch.CS.Appclusive.UI#78]

**Comment by trumpetchris** [comment]
- tenantId is string, not int
- Check if ids are long instead of int.

**Comment by ChrEggenberger** [comment]
Tenant is the only id which is not long it is Guid.
-> on tenant controller rId should be string : etails(string id, int rId = 0,
-> on all others long

**Comment by trumpetchris** [comment]
rId must not have the same type as the entity, I was wrong. We can also return from a customer to a tenant. So the id type for customer is long, but the rId to the tenant is a guid.
-> So rId must be string!
