### ISSUE TITLE
Approve/Decline Approval

### ISSUE THREAD

**Issue by rufer7** [dfensgmbh/biz.dfch.CS.Appclusive.UI#80]
Actually approvals are approved/declined by executing a PUT/PATCH with Status = Condition. This should be improved by executing `~/Approvals(ID)/InvokeAction`

**Comment by rufer7** [comment]
Example

```
http://host:port/api/Core/Approvals(ID)/InvokeAction

{
  "Parameters": "approved! enjoy working",
  "Name": "Continue"
}
```

**Comment by ChrEggenberger** [comment]
Coded, but can not be tested because no approval has a job see issue 8 in biz.dfch.CS.Appclusive.Api

**Comment by rufer7** [comment]
@ChrEggenberger should now work (see dfensgmbh/biz.dfch.CS.Appclusive.Api#8 for reason why it didn't work)
