### ISSUE TITLE
LAB3 - 401.2 Unauthorized

### ISSUE THREAD

**Issue by rufer7** [dfensgmbh/biz.dfch.CS.Appclusive.UI#84]
Yesterday I deployed the newest version (including updated reference to [`biz.dfch.CS.Appclusive.Api`](https://github.com/dfensgmbh/biz.dfch.CS.Appclusive.Api) of the UI to LAB3. When trying to connect to the UI the following error occurs

```
HTTP Error 401.2 - Unauthorized
You are not authorized to view this page due to invalid authentication headers.
```

Can you please try to figure out why this is happening and document the reason and solution on this issue?

**Comment by ChrEggenberger** [comment]
Authentication on IIS virtual directory mnust be like this:
Anonymous Authentication:  Enabled
Forms Authentication            Enabled
everything else   Disabled
