### ISSUE TITLE
Update according Appclusive 1.2.6

### ISSUE THREAD

**Issue by rufer7** [dfensgmbh/biz.dfch.CS.Appclusive.UI#89]
Today I released a new version (`1.2.6`) of [biz.dfch.CS.Appclusive.Api](https://github.com/dfensgmbh/biz.dfch.CS.Appclusive.Api). Please update the UI accordingly.

Release Notes can be found [here](https://github.com/dfensgmbh/biz.dfch.CS.Appclusive.Api/releases/tag/1.2.6)

* [x] Update reference to [biz.dfch.CS.Appclusive.Api](https://github.com/dfensgmbh/biz.dfch.CS.Appclusive.Api)
* [x] Update UI according [biz.dfch.CS.Appclusive.Api](https://github.com/dfensgmbh/biz.dfch.CS.Appclusive.Api) 1.2.6
* [x] ACE
* [x] ACL 
* [x] Node
* [x] Role

**Comment by ChrEggenberger** [comment]
@rufer7 folling errors occur:
* [ ] PATCH: [CorrelationId: 0e20c1cd-4424-4f6a-a60e-053c461fed2b] Assertion failed: entityWithChanges.TrusteeId == entity.TrusteeId 
* [ ] POST/PATCH Enum underlying type and the object must be same type or object must be a String. Type passed in was 'System.Int64'; the enum underlying type was 'System.Int32'.","type":"System.ArgumentException"
-> all Enums need underlying type or change type of properties
```
public enum AceTypeEnum : long
```

**Comment by rufer7** [comment]
@ChrEggenberger 
* as defined in code by @dfch it's not allowed to change the `TrusteeId` on PUT/PATCH operations
* POST/PATCH Enum underlying type ... will be fixed in next release
* Exactly there is no navigation property from `ACE` to `ACL` probably @dfch knows the reason or should we add the navigation property?

**Comment by dfch** [comment]
@ChrEggenberger @rufer7 I do not see the need for a navprop from ACE to ACL as we always drill *down* from ACL to ACE. ACE is more like a structural or list element to define the actual contents of an ACL. I therefore removed it.

**Comment by ChrEggenberger** [comment]
Thats ok for me. I will remove ACE list from the navigation because this doesn't help then either

**Comment by rufer7** [comment]
With the next release the following call will work

```
POST http://localhost:53422/api/Core/Aces HTTP/1.1

{
  "TrusteeId":"1","TrusteeType":"0","Type":"2","PermissionId":"0","AclId":"1","Id":"0","Tid":"22222222-2222-2222-2222-222222222222","Name":"ACE","Description":"optional","CreatedById":"1","ModifiedById":"1","Created":"2016-01-15T08:53:31.3849449+01:00","Modified":"2016-01-15T08:53:31.3849449+01:00","RowVersion":null
}
```
