### ISSUE TITLE
Screens for Catalogues (CRUD)

### ISSUE THREAD

**Issue by rufer7** [dfensgmbh/biz.dfch.CS.Appclusive.UI#9]
- [x] Read
- [x] Create
- [x] Update (postponed)
- [x] Delete (postponed)

![catalogues](https://cloud.githubusercontent.com/assets/5937292/11469064/31dee94c-9754-11e5-840a-7a9b13446aec.png)
![catalogues_2](https://cloud.githubusercontent.com/assets/5937292/11469067/31e42e20-9754-11e5-90d3-59a62ce2490f.png)
![catalogues_3](https://cloud.githubusercontent.com/assets/5937292/11469066/31e2f474-9754-11e5-9016-fc057e5d7fae.png)
![catalogues_4](https://cloud.githubusercontent.com/assets/5937292/11469065/31dfe8ce-9754-11e5-8434-268b4b64757f.png)

**Comment by ChrEggenberger** [comment]
Which Status-Values are possible? "Published" works. What else?

**Comment by rufer7** [comment]
The follwing status values are possible at the moment:

`Published`
`Revoked`
`Hidden`
