### ISSUE TITLE
Support switching of active Tenant in UI and API Calls

### ISSUE THREAD

**Issue by ChrEggenberger** [dfensgmbh/biz.dfch.CS.Appclusive.UI#92]
* [x] Tenant-switch on UI -> active tenant
* [x] active tenant in Header for all API call
* [x] filter all data by active tenant
* [x] support "all tentants"-Filter?

**Comment by ChrEggenberger** [comment]
needs API update first

**Comment by rufer7** [comment]
@ChrEggenberger I released the API a few days ago and today I updated the reference in the UI project, so you could start tackle this issue

**Comment by ChrEggenberger** [comment]
filter all data by active tenant is done on server side
