### ISSUE TITLE
Enhancement on node tree and node details

### ISSUE THREAD

**Issue by rufer7** [dfensgmbh/biz.dfch.CS.Appclusive.UI#95]
Details:
* [x] Navigation from detail to ACL and back should end up on node detail again 
* [x] change columns in ACE-list: Type, Trustee, Trustee type, Permission
* [x] never show name of ACL or ACE in Node
* [x] ACL = Access Control List
* [x] ACE = Access Control Entity
* [x] id no ACL is available "create new"
* [x] Navigation to ACL throug EDIT Button instead of name
* [x] Show icons of Trustee type (Role or User)

Tree:
* [x] remove recursive occurences
* [x] paging in tree (api delivers only 45)
* [x] search in tree (like list) 
-> either load full tree and filter or load parents of each search result 
* [x] Show icons of node according to EntityKind

**Comment by ChrEggenberger** [comment]
Search function 
* loads PortalConfig.SearchLoadSize search results, 
* finds their parents and creates a tree. 
* Opening the nodes loads all childnodes without search terms
* if there are more it may adds another root node which is a bit strange but occurs ony if your search is not useful anyway (too many results)
