### ISSUE TITLE
Confirmation/Information when adding an Item to Cart

### ISSUE THREAD

**Issue by rufer7** [dfensgmbh/biz.dfch.CS.Appclusive.UI#99]
Actually there is no confirmation/information for the user if he adds an item to the cart.

**Comment by ChrEggenberger** [comment]
There is a message on the top right corner. Ic ould place it near the mouse pointer

**Comment by rufer7** [comment]
@ChrEggenberger ah I didn't see this message, sorry. hmm...probably we could improve the appearance...
